Doc interval 80
ReactiveX/rxjs-docs pull request #296
Opened 2018-03-04 18:07 UTC by cschomer

Add docs for operator : creation - interval

2018-03-05 19:11 UTC, JWO719 commented
Could you change your commit messages. There are several :, these make travis break. If you need any help, just inform me. Thanks for your work!!!

2018-03-06 00:46 UTC, cschomer commented
Yes sorry about that, should be corrected and passing now.

2018-03-08 02:41 UTC, ashwin-sureshkumar requested changes
Thanks for the PR. Please address requested changes.

2018-03-13 11:55 UTC, cschomer commented on src/operator-docs/creation/interval.ts
> +        url: 'http://jsbin.com/gaxinafovo/1/edit?html,js,console,output'
Updated path to use embed

2018-03-13 11:55 UTC, cschomer commented on src/operator-docs/creation/interval.ts
> +          import { interval } from 'rxjs/internal/observable/interval';
Changed path to correct path

2018-03-14 17:07 UTC, ladyleet commented
@cschomer have time to make these changes yet? we'd love to merge!

2018-03-14 23:39 UTC, cschomer commented
@ladyleet Hi I checked in 2 commits for the requested changes, are those not showing up? I think with those two that should address the two requested changes.

[commit ea9c472d97e6c7b0f00feabc55bed642ab0781d1](https://github.com/ReactiveX/rxjs-docs/pull/296/files/fde5aa85997d5986a42f26ea0521969f450a2aa9)

2018-03-15 13:22 UTC, ashwin-sureshkumar approved these changes

2018-03-15 13:23 UTC, ashwin-sureshkumar commented
@cschomer - Thanks for the PR. 

Please use `Close #<issue-number>` in your future commits in the description. This will auto-close the issue once the PR is merged in. 

For this one, we can manually close the issue.

2018-03-19 19:47 UTC, niklas-wortmann requested changes
Just a little change. After that one, I think it can be merged.

2018-03-19 19:47 UTC, JWO719 commented on src/operator-docs/creation/interval.ts
> +          import { pipe } from 'rxjs';
pipe doesn't need to be imported, I think :D

2022-10-02 19:03 UTC, closed without merging